from django.conf import settings
from django.utils.translation import gettext as _

OBJECT_TYPES_REGISTRY = {}

DEFAULT_ACLS = {}

class Utils:
    RESOURCE_CONCEPT = settings.RESOURCE_CONCEPT

    PERMISSION_ACTION_LIST = 'LIST'
    PERMISSION_ACTION_CREATE = 'CREATE'
    PERMISSION_ACTION_VIEW = 'VIEW'
    PERMISSION_ACTION_UPDATE = 'UPDATE'
    PERMISSION_ACTION_DELETE = 'DELETE'
    PERMISSION_ACTION_EXECUTE = 'EXECUTE'
    PERMISSION_ACTION = [
        (PERMISSION_ACTION_LIST, _('List')),
        (PERMISSION_ACTION_CREATE, _('Create')),
        (PERMISSION_ACTION_VIEW, _('View')),
        (PERMISSION_ACTION_UPDATE, _('Update')),
        (PERMISSION_ACTION_DELETE, _('Delete')),
        (PERMISSION_ACTION_EXECUTE, _('Execute'))
    ]
